/* DO NOT EDIT, file generated by nestjs-i18n */
  
/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "all": {
        "clubs": {
            "search": string;
        };
        "game": {
            "recent": {
                "title": string;
            };
            "upcoming": {
                "title": string;
            };
        };
        "landing": {
            "description": string;
        };
        "players": {
            "search": string;
        };
        "points": {
            "table": {
                "level": string;
                "points-needed-down": string;
                "points-needed-up": string;
                "points-won": string;
            };
        };
        "settings": {
            "general": {
                "title": string;
            };
            "languages": {
                "en": string;
                "fr_BE": string;
                "nl_BE": string;
                "title": string;
            };
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
