/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "all": {
        "clubs": {
            "search": string;
        };
        "game": {
            "recent": {
                "title": string;
            };
            "upcoming": {
                "title": string;
            };
        };
        "head-to-head": {
            "amount-of-games": string;
            "club": string;
            "filter-groups": {
                "game-type": string;
                "opponent-filters": string;
                "partner-filters": string;
                "time-performance": string;
                "view-mode": string;
            };
            "filters": {
                "all": string;
                "club": string;
                "competition": string;
                "double": string;
                "games": string;
                "gameType": string;
                "linktype": string;
                "mix": string;
                "opponent-club": string;
                "opponents": string;
                "partner-club": string;
                "partners": string;
                "single": string;
                "start-date": string;
                "title": string;
                "tournament": string;
                "view-mode": string;
                "with-partner": string;
            };
            "grid": {
                "average": string;
                "loading": string;
                "total": string;
            };
            "info": {
                "club-display": string;
                "description": string;
                "opponents-mode": string;
                "partner-filter": string;
                "partners-mode": string;
                "title": string;
            };
            "name": string;
            "partner": string;
            "title": string;
            "win-rate": string;
            "win-rate-against": string;
        };
        "players": {
            "my-club": string;
            "my-clubs": string;
            "my-profile": string;
            "search": string;
        };
        "points": {
            "needed-for-downgrade": string;
            "needed-for-upgrade": string;
            "table": {
                "level": string;
                "points-needed-down": string;
                "points-needed-up": string;
                "points-won": string;
            };
        };
        "ranking": {
            "breakdown": {
                "downgrade": string;
                "upgrade": string;
            };
        };
        "settings": {
            "general": {
                "title": string;
            };
            "languages": {
                "en": string;
                "fr_BE": string;
                "nl_BE": string;
                "title": string;
            };
        };
        "system": {
            "update": {
                "available": string;
                "description": string;
                "refresh": string;
            };
        };
        "player": {
            "edit": {
                "title": string;
                "subtitle": string;
                "actions": {
                    "save-all": string;
                    "save-current": string;
                    "cancel": string;
                };
                "tabs": {
                    "profile": string;
                    "claims": string;
                };
                "messages": {
                    "loading": string;
                    "unsaved-changes": string;
                };
                "claims": {
                    "title": string;
                    "subtitle": string;
                    "description": string;
                    "actions": {
                        "select-all": string;
                        "select-none": string;
                        "save": string;
                        "cancel": string;
                    };
                    "messages": {
                        "no-claims": string;
                        "no-permission": string;
                        "saving": string;
                        "loading": string;
                    };
                };
                "profile": {
                    "description": string;
                    "personal": {
                        "title": string;
                    };
                    "firstName": string;
                    "firstName.placeholder": string;
                    "firstName.required": string;
                    "lastName": string;
                    "lastName.placeholder": string;
                    "lastName.required": string;
                    "gender": string;
                    "gender.placeholder": string;
                    "birthDate": string;
                    "birthDate.placeholder": string;
                    "contact": {
                        "title": string;
                    };
                    "email": string;
                    "email.placeholder": string;
                    "email.invalid": string;
                    "phone": string;
                    "phone.placeholder": string;
                    "editable": string;
                    "competition": {
                        "title": string;
                    };
                    "competitionPlayer": string;
                    "competitionPlayer.description": string;
                    "permissions": {
                        "title": string;
                        "description": string;
                        "canEditContact": string;
                        "canEditAdmin": string;
                    };
                    "messages": {
                        "saving": string;
                    };
                };
            };
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
