import { MigrationInterface, QueryRunner } from "typeorm";

export class Test1720189504048 implements MigrationInterface {
    name = 'Test1720189504048'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystemRankingGroupMemberships" DROP CONSTRAINT "GroupSystems_groupId_fkey"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystemRankingGroupMemberships" DROP CONSTRAINT "GroupSystems_systemId_fkey"`);
        await queryRunner.query(`ALTER TABLE "ClubPlayerMemberships" DROP CONSTRAINT "ClubMemberships_clubId_fkey"`);
        await queryRunner.query(`ALTER TABLE "ClubPlayerMemberships" DROP CONSTRAINT "ClubMemberships_playerId_fkey"`);
        await queryRunner.query(`ALTER TABLE "event"."Games" DROP CONSTRAINT "Games_courtId_fkey"`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" DROP CONSTRAINT "GamePlayerMemberships_systemId_fkey"`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" DROP CONSTRAINT "GamePlayers_gameId_fkey"`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" DROP CONSTRAINT "GamePlayers_playerId_fkey"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" DROP CONSTRAINT "LastPlaces_playerId_fkey"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" DROP CONSTRAINT "LastPlaces_systemId_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."clubs_name"`);
        await queryRunner.query(`DROP INDEX "public"."player_club_index"`);
        await queryRunner.query(`DROP INDEX "event"."game_parent_index"`);
        await queryRunner.query(`DROP INDEX "event"."game_players_game_id"`);
        await queryRunner.query(`DROP INDEX "event"."game_players_player_id"`);
        await queryRunner.query(`DROP INDEX "public"."players_first_name"`);
        await queryRunner.query(`DROP INDEX "public"."players_id"`);
        await queryRunner.query(`DROP INDEX "public"."players_last_name"`);
        await queryRunner.query(`DROP INDEX "public"."players_member_id"`);
        await queryRunner.query(`DROP INDEX "public"."players_slug"`);
        await queryRunner.query(`DROP INDEX "ranking"."lastPlaces_ranking_index"`);
        await queryRunner.query(`ALTER TABLE "Clubs" DROP CONSTRAINT "club_number_unique"`);
        await queryRunner.query(`ALTER TABLE "ClubPlayerMemberships" DROP CONSTRAINT "ClubMemberships_playerId_clubId_start_key"`);
        await queryRunner.query(`ALTER TABLE "Players" DROP CONSTRAINT "Players_firstName_lastName_memberId_key"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" DROP CONSTRAINT "lastPlaces_unique_constraint"`);
        await queryRunner.query(`ALTER TABLE "Clubs" DROP COLUMN "useForTeamName"`);
        await queryRunner.query(`DROP TYPE "public"."enum_Clubs_useForTeamName"`);
        await queryRunner.query(`ALTER TABLE "ClubPlayerMemberships" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "ClubPlayerMemberships" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "ClubPlayerMemberships" DROP COLUMN "membershipType"`);
        await queryRunner.query(`DROP TYPE "public"."enum_ClubPlayerMemberships_membershipType"`);
        await queryRunner.query(`ALTER TABLE "event"."Games" DROP COLUMN "gameType"`);
        await queryRunner.query(`DROP TYPE "event"."enum_Games_gameType"`);
        await queryRunner.query(`ALTER TABLE "event"."Games" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "event"."enum_Games_status"`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" DROP COLUMN "team"`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" DROP COLUMN "player"`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" DROP COLUMN "single"`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" DROP COLUMN "double"`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" DROP COLUMN "mix"`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" DROP COLUMN "systemId"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingGroups" ADD "rankingSystemRankingGroupMembershipRankingSystemRankingGroupMembershipId" uuid`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystemRankingGroupMemberships" ADD "rankingSystemRankingGroupMembershipId" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystemRankingGroupMemberships" DROP CONSTRAINT "GroupSystems_pkey"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystemRankingGroupMemberships" ADD CONSTRAINT "GroupSystems_pkey" PRIMARY KEY ("groupId", "systemId", "rankingSystemRankingGroupMembershipId")`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystemRankingGroupMemberships" ADD "rankingSystemId" uuid`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystemRankingGroupMemberships" ADD "rankingGroupId" uuid`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "rankingSystemRankingGroupMembershipRankingSystemRankingGroupMembershipId" uuid`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" DROP CONSTRAINT "GamePlayers_pkey"`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" ADD CONSTRAINT "GamePlayers_pkey" PRIMARY KEY ("playerId", "gameId", "id")`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" ADD "end" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" ADD "confirmed" boolean NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" ADD "start" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingGroups" DROP CONSTRAINT "Groups_pkey"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingGroups" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingGroups" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingGroups" ADD CONSTRAINT "PK_444b4810c1a20aa442417cd6b94" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingGroups" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingGroups" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingGroups" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingGroups" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingGroups" DROP CONSTRAINT "Groups_name_key"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingGroups" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingGroups" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystemRankingGroupMemberships" DROP CONSTRAINT "GroupSystems_pkey"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystemRankingGroupMemberships" ADD CONSTRAINT "GroupSystems_pkey" PRIMARY KEY ("groupId", "rankingSystemRankingGroupMembershipId")`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystemRankingGroupMemberships" DROP CONSTRAINT "GroupSystems_pkey"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystemRankingGroupMemberships" ADD CONSTRAINT "PK_bf1f20730bbad18ddf6fe95b45a" PRIMARY KEY ("rankingSystemRankingGroupMembershipId")`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystemRankingGroupMemberships" DROP COLUMN "groupId"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystemRankingGroupMemberships" ADD "groupId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP CONSTRAINT "Systems_name_key"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ALTER COLUMN "amountOfLevels" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "procentWinning"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "procentWinning" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "procentWinningPlus1"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "procentWinningPlus1" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "procentLosing"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "procentLosing" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ALTER COLUMN "minNumberOfGamesUsedForUpgrade" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ALTER COLUMN "minNumberOfGamesUsedForDowngrade" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ALTER COLUMN "maxDiffLevels" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ALTER COLUMN "maxDiffLevelsHighest" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ALTER COLUMN "latestXGamesToUse" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ALTER COLUMN "maxLevelUpPerChange" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ALTER COLUMN "maxLevelDownPerChange" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ALTER COLUMN "gamesForInactivty" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ALTER COLUMN "inactivityAmount" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "inactivityUnit"`);
        await queryRunner.query(`DROP TYPE "ranking"."enum_Systems_inactivityUnit"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "inactivityUnit" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "inactiveBehavior"`);
        await queryRunner.query(`DROP TYPE "ranking"."enum_RankingSystems_inactiveBehavior"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "inactiveBehavior" character varying`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "calculationLastUpdate"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "calculationLastUpdate" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ALTER COLUMN "calculationDayOfWeek" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ALTER COLUMN "calculationIntervalAmount" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "calculationIntervalUnit"`);
        await queryRunner.query(`DROP TYPE "ranking"."enum_Systems_calculationIntervalUnit"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "calculationIntervalUnit" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "periodAmount"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "periodAmount" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "periodUnit"`);
        await queryRunner.query(`DROP TYPE "ranking"."enum_Systems_periodUnit"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "periodUnit" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "updateLastUpdate"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "updateLastUpdate" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ALTER COLUMN "updateDayOfWeek" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ALTER COLUMN "updateIntervalAmount" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "updateIntervalUnit"`);
        await queryRunner.query(`DROP TYPE "ranking"."enum_Systems_updateIntervalUnit"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "updateIntervalUnit" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "rankingSystem"`);
        await queryRunner.query(`DROP TYPE "ranking"."enum_Systems_rankingSystem"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "rankingSystem" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ALTER COLUMN "primary" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ALTER COLUMN "calculateUpdates" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ALTER COLUMN "runCurrently" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ALTER COLUMN "runCurrently" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "differenceForUpgradeSingle"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "differenceForUpgradeSingle" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "differenceForUpgradeDouble"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "differenceForUpgradeDouble" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "differenceForUpgradeMix"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "differenceForUpgradeMix" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "differenceForDowngradeSingle"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "differenceForDowngradeSingle" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "differenceForDowngradeDouble"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "differenceForDowngradeDouble" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "differenceForDowngradeMix"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "differenceForDowngradeMix" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "startingType"`);
        await queryRunner.query(`DROP TYPE "ranking"."enum_Systems_startingType"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "startingType" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Clubs" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "Clubs" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "Clubs" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "Clubs" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "Clubs" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "Clubs" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Clubs" DROP COLUMN "teamName"`);
        await queryRunner.query(`ALTER TABLE "Clubs" ADD "teamName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Clubs" DROP COLUMN "fullName"`);
        await queryRunner.query(`ALTER TABLE "Clubs" ADD "fullName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Clubs" DROP COLUMN "contactCompetition"`);
        await queryRunner.query(`ALTER TABLE "Clubs" ADD "contactCompetition" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Clubs" DROP COLUMN "abbreviation"`);
        await queryRunner.query(`ALTER TABLE "Clubs" ADD "abbreviation" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Clubs" ALTER COLUMN "clubId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Clubs" ADD CONSTRAINT "UQ_8df52627355046c679aeb6c2401" UNIQUE ("clubId")`);
        await queryRunner.query(`ALTER TABLE "Clubs" DROP CONSTRAINT "Clubs_slug_key"`);
        await queryRunner.query(`ALTER TABLE "Clubs" DROP COLUMN "slug"`);
        await queryRunner.query(`ALTER TABLE "Clubs" ADD "slug" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Clubs" DROP COLUMN "state"`);
        await queryRunner.query(`ALTER TABLE "Clubs" ADD "state" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Clubs" DROP COLUMN "country"`);
        await queryRunner.query(`ALTER TABLE "Clubs" ADD "country" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ClubPlayerMemberships" DROP COLUMN "end"`);
        await queryRunner.query(`ALTER TABLE "ClubPlayerMemberships" ADD "end" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ClubPlayerMemberships" ALTER COLUMN "confirmed" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "ClubPlayerMemberships" DROP COLUMN "start"`);
        await queryRunner.query(`ALTER TABLE "ClubPlayerMemberships" ADD "start" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event"."Games" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "event"."Games" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "event"."Games" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "event"."Games" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "event"."Games" DROP COLUMN "playedAt"`);
        await queryRunner.query(`ALTER TABLE "event"."Games" ADD "playedAt" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event"."Games" ALTER COLUMN "set1Team1" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event"."Games" ALTER COLUMN "set1Team2" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event"."Games" ALTER COLUMN "set2Team1" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event"."Games" ALTER COLUMN "set2Team2" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event"."Games" ALTER COLUMN "set3Team1" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event"."Games" ALTER COLUMN "set3Team2" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event"."Games" ALTER COLUMN "winner" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event"."Games" ALTER COLUMN "order" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event"."Games" DROP COLUMN "round"`);
        await queryRunner.query(`ALTER TABLE "event"."Games" ADD "round" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event"."Games" DROP COLUMN "linkId"`);
        await queryRunner.query(`ALTER TABLE "event"."Games" ADD "linkId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event"."Games" DROP COLUMN "linkType"`);
        await queryRunner.query(`ALTER TABLE "event"."Games" ADD "linkType" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event"."Games" DROP COLUMN "courtId"`);
        await queryRunner.query(`ALTER TABLE "event"."Games" ADD "courtId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event"."Games" DROP COLUMN "visualCode"`);
        await queryRunner.query(`ALTER TABLE "event"."Games" ADD "visualCode" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" DROP CONSTRAINT "GamePlayers_pkey"`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" ADD CONSTRAINT "GamePlayers_pkey" PRIMARY KEY ("gameId", "id")`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" DROP CONSTRAINT "GamePlayers_pkey"`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" ADD CONSTRAINT "PK_9944c9e20e2430dd1a82c4c9026" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "Players" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "Players" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "Players" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "Players" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "Players" DROP COLUMN "sub"`);
        await queryRunner.query(`ALTER TABLE "Players" ADD "sub" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Players" ADD CONSTRAINT "UQ_ebfaf552b0ab613e69aa1ba4202" UNIQUE ("sub")`);
        await queryRunner.query(`ALTER TABLE "Players" DROP COLUMN "firstName"`);
        await queryRunner.query(`ALTER TABLE "Players" ADD "firstName" character varying`);
        await queryRunner.query(`ALTER TABLE "Players" DROP COLUMN "lastName"`);
        await queryRunner.query(`ALTER TABLE "Players" ADD "lastName" character varying`);
        await queryRunner.query(`ALTER TABLE "Players" DROP CONSTRAINT "Players_slug_key"`);
        await queryRunner.query(`ALTER TABLE "Players" DROP COLUMN "slug"`);
        await queryRunner.query(`ALTER TABLE "Players" ADD "slug" character varying`);
        await queryRunner.query(`ALTER TABLE "Players" DROP COLUMN "memberId"`);
        await queryRunner.query(`ALTER TABLE "Players" ADD "memberId" character varying`);
        await queryRunner.query(`ALTER TABLE "Players" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "Players" ADD "email" character varying`);
        await queryRunner.query(`ALTER TABLE "Players" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "Players" ADD "phone" character varying`);
        await queryRunner.query(`ALTER TABLE "Players" DROP COLUMN "gender"`);
        await queryRunner.query(`ALTER TABLE "Players" ADD "gender" character varying`);
        await queryRunner.query(`ALTER TABLE "Players" DROP COLUMN "birthDate"`);
        await queryRunner.query(`ALTER TABLE "Players" ADD "birthDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "Players" ALTER COLUMN "competitionPlayer" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ADD "updatedAt" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" DROP COLUMN "rankingDate"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ADD "rankingDate" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" DROP COLUMN "gender"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ADD "gender" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "singlePoints" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "mixPoints" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "doublePoints" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "singlePointsDowngrade" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "mixPointsDowngrade" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "doublePointsDowngrade" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "singleRank" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "mixRank" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "doubleRank" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "totalSingleRanking" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "totalMixRanking" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "totalDoubleRanking" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "totalWithinSingleLevel" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "totalWithinMixLevel" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "totalWithinDoubleLevel" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "single" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "mix" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "double" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "singleInactive" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "mixInactive" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "doubleInactive" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "playerId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ADD CONSTRAINT "UQ_43b21895b5a5be60041562616c2" UNIQUE ("playerId")`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "systemId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingGroups" ADD CONSTRAINT "FK_400f2518c94663b8fcaea2cb8b2" FOREIGN KEY ("rankingSystemRankingGroupMembershipRankingSystemRankingGroupMembershipId") REFERENCES "ranking"."RankingSystemRankingGroupMemberships"("rankingSystemRankingGroupMembershipId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystemRankingGroupMemberships" ADD CONSTRAINT "FK_7ec9a18214070b1e5cbe2443d75" FOREIGN KEY ("rankingSystemId") REFERENCES "ranking"."RankingSystems"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystemRankingGroupMemberships" ADD CONSTRAINT "FK_6ac75fab3efbc1a2b48fae59a83" FOREIGN KEY ("rankingGroupId") REFERENCES "ranking"."RankingGroups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD CONSTRAINT "FK_6fd96071d25589e0f75cc70cc47" FOREIGN KEY ("rankingSystemRankingGroupMembershipRankingSystemRankingGroupMembershipId") REFERENCES "ranking"."RankingSystemRankingGroupMemberships"("rankingSystemRankingGroupMembershipId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ClubPlayerMemberships" ADD CONSTRAINT "FK_0c39db4aebb22ddacb3354d9949" FOREIGN KEY ("playerId") REFERENCES "Players"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ClubPlayerMemberships" ADD CONSTRAINT "FK_d9a625ad8485da798534c1587d5" FOREIGN KEY ("clubId") REFERENCES "Clubs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" ADD CONSTRAINT "FK_838500ca255539b133c7b86f8b7" FOREIGN KEY ("playerId") REFERENCES "Players"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" ADD CONSTRAINT "FK_afe644cba7b2ed50c0051cf9b97" FOREIGN KEY ("gameId") REFERENCES "event"."Games"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ADD CONSTRAINT "FK_43b21895b5a5be60041562616c2" FOREIGN KEY ("playerId") REFERENCES "Players"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ADD CONSTRAINT "FK_72fcbcbca75596f83be474b1e1c" FOREIGN KEY ("systemId") REFERENCES "ranking"."RankingSystems"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" DROP CONSTRAINT "FK_72fcbcbca75596f83be474b1e1c"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" DROP CONSTRAINT "FK_43b21895b5a5be60041562616c2"`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" DROP CONSTRAINT "FK_afe644cba7b2ed50c0051cf9b97"`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" DROP CONSTRAINT "FK_838500ca255539b133c7b86f8b7"`);
        await queryRunner.query(`ALTER TABLE "ClubPlayerMemberships" DROP CONSTRAINT "FK_d9a625ad8485da798534c1587d5"`);
        await queryRunner.query(`ALTER TABLE "ClubPlayerMemberships" DROP CONSTRAINT "FK_0c39db4aebb22ddacb3354d9949"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP CONSTRAINT "FK_6fd96071d25589e0f75cc70cc47"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystemRankingGroupMemberships" DROP CONSTRAINT "FK_6ac75fab3efbc1a2b48fae59a83"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystemRankingGroupMemberships" DROP CONSTRAINT "FK_7ec9a18214070b1e5cbe2443d75"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingGroups" DROP CONSTRAINT "FK_400f2518c94663b8fcaea2cb8b2"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "systemId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" DROP CONSTRAINT "UQ_43b21895b5a5be60041562616c2"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "playerId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "doubleInactive" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "mixInactive" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "singleInactive" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "double" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "mix" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "single" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "totalWithinDoubleLevel" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "totalWithinMixLevel" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "totalWithinSingleLevel" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "totalDoubleRanking" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "totalMixRanking" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "totalSingleRanking" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "doubleRank" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "mixRank" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "singleRank" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "doublePointsDowngrade" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "mixPointsDowngrade" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "singlePointsDowngrade" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "doublePoints" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "mixPoints" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ALTER COLUMN "singlePoints" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" DROP COLUMN "gender"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ADD "gender" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" DROP COLUMN "rankingDate"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ADD "rankingDate" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ADD "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "Players" ALTER COLUMN "competitionPlayer" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "Players" DROP COLUMN "birthDate"`);
        await queryRunner.query(`ALTER TABLE "Players" ADD "birthDate" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "Players" DROP COLUMN "gender"`);
        await queryRunner.query(`ALTER TABLE "Players" ADD "gender" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "Players" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "Players" ADD "phone" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "Players" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "Players" ADD "email" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "Players" DROP COLUMN "memberId"`);
        await queryRunner.query(`ALTER TABLE "Players" ADD "memberId" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "Players" DROP COLUMN "slug"`);
        await queryRunner.query(`ALTER TABLE "Players" ADD "slug" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "Players" ADD CONSTRAINT "Players_slug_key" UNIQUE ("slug")`);
        await queryRunner.query(`ALTER TABLE "Players" DROP COLUMN "lastName"`);
        await queryRunner.query(`ALTER TABLE "Players" ADD "lastName" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "Players" DROP COLUMN "firstName"`);
        await queryRunner.query(`ALTER TABLE "Players" ADD "firstName" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "Players" DROP CONSTRAINT "UQ_ebfaf552b0ab613e69aa1ba4202"`);
        await queryRunner.query(`ALTER TABLE "Players" DROP COLUMN "sub"`);
        await queryRunner.query(`ALTER TABLE "Players" ADD "sub" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "Players" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "Players" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "Players" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "Players" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" DROP CONSTRAINT "PK_9944c9e20e2430dd1a82c4c9026"`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" ADD CONSTRAINT "GamePlayers_pkey" PRIMARY KEY ("gameId", "id")`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" DROP CONSTRAINT "GamePlayers_pkey"`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" ADD CONSTRAINT "GamePlayers_pkey" PRIMARY KEY ("playerId", "gameId", "id")`);
        await queryRunner.query(`ALTER TABLE "event"."Games" DROP COLUMN "visualCode"`);
        await queryRunner.query(`ALTER TABLE "event"."Games" ADD "visualCode" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "event"."Games" DROP COLUMN "courtId"`);
        await queryRunner.query(`ALTER TABLE "event"."Games" ADD "courtId" uuid`);
        await queryRunner.query(`ALTER TABLE "event"."Games" DROP COLUMN "linkType"`);
        await queryRunner.query(`ALTER TABLE "event"."Games" ADD "linkType" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "event"."Games" DROP COLUMN "linkId"`);
        await queryRunner.query(`ALTER TABLE "event"."Games" ADD "linkId" uuid`);
        await queryRunner.query(`ALTER TABLE "event"."Games" DROP COLUMN "round"`);
        await queryRunner.query(`ALTER TABLE "event"."Games" ADD "round" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "event"."Games" ALTER COLUMN "order" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event"."Games" ALTER COLUMN "winner" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event"."Games" ALTER COLUMN "set3Team2" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event"."Games" ALTER COLUMN "set3Team1" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event"."Games" ALTER COLUMN "set2Team2" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event"."Games" ALTER COLUMN "set2Team1" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event"."Games" ALTER COLUMN "set1Team2" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event"."Games" ALTER COLUMN "set1Team1" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "event"."Games" DROP COLUMN "playedAt"`);
        await queryRunner.query(`ALTER TABLE "event"."Games" ADD "playedAt" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "event"."Games" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "event"."Games" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "event"."Games" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "event"."Games" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ClubPlayerMemberships" DROP COLUMN "start"`);
        await queryRunner.query(`ALTER TABLE "ClubPlayerMemberships" ADD "start" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ClubPlayerMemberships" ALTER COLUMN "confirmed" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "ClubPlayerMemberships" DROP COLUMN "end"`);
        await queryRunner.query(`ALTER TABLE "ClubPlayerMemberships" ADD "end" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "Clubs" DROP COLUMN "country"`);
        await queryRunner.query(`ALTER TABLE "Clubs" ADD "country" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "Clubs" DROP COLUMN "state"`);
        await queryRunner.query(`ALTER TABLE "Clubs" ADD "state" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "Clubs" DROP COLUMN "slug"`);
        await queryRunner.query(`ALTER TABLE "Clubs" ADD "slug" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "Clubs" ADD CONSTRAINT "Clubs_slug_key" UNIQUE ("slug")`);
        await queryRunner.query(`ALTER TABLE "Clubs" DROP CONSTRAINT "UQ_8df52627355046c679aeb6c2401"`);
        await queryRunner.query(`ALTER TABLE "Clubs" ALTER COLUMN "clubId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Clubs" DROP COLUMN "abbreviation"`);
        await queryRunner.query(`ALTER TABLE "Clubs" ADD "abbreviation" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "Clubs" DROP COLUMN "contactCompetition"`);
        await queryRunner.query(`ALTER TABLE "Clubs" ADD "contactCompetition" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "Clubs" DROP COLUMN "fullName"`);
        await queryRunner.query(`ALTER TABLE "Clubs" ADD "fullName" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "Clubs" DROP COLUMN "teamName"`);
        await queryRunner.query(`ALTER TABLE "Clubs" ADD "teamName" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "Clubs" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "Clubs" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "Clubs" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "Clubs" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "Clubs" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "Clubs" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "startingType"`);
        await queryRunner.query(`CREATE TYPE "ranking"."enum_Systems_startingType" AS ENUM('formula', 'tableLFBB', 'tableBVL')`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "startingType" "ranking"."enum_Systems_startingType" DEFAULT 'formula'`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "differenceForDowngradeMix"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "differenceForDowngradeMix" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "differenceForDowngradeDouble"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "differenceForDowngradeDouble" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "differenceForDowngradeSingle"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "differenceForDowngradeSingle" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "differenceForUpgradeMix"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "differenceForUpgradeMix" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "differenceForUpgradeDouble"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "differenceForUpgradeDouble" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "differenceForUpgradeSingle"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "differenceForUpgradeSingle" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ALTER COLUMN "runCurrently" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ALTER COLUMN "runCurrently" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ALTER COLUMN "calculateUpdates" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ALTER COLUMN "primary" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "rankingSystem"`);
        await queryRunner.query(`CREATE TYPE "ranking"."enum_Systems_rankingSystem" AS ENUM('BVL', 'ORIGINAL', 'LFBB', 'VISUAL')`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "rankingSystem" "ranking"."enum_Systems_rankingSystem"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "updateIntervalUnit"`);
        await queryRunner.query(`CREATE TYPE "ranking"."enum_Systems_updateIntervalUnit" AS ENUM('months', 'weeks', 'days')`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "updateIntervalUnit" "ranking"."enum_Systems_updateIntervalUnit"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ALTER COLUMN "updateIntervalAmount" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ALTER COLUMN "updateDayOfWeek" SET DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "updateLastUpdate"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "updateLastUpdate" TIMESTAMP WITH TIME ZONE DEFAULT '2016-08-31 22:00:00+00'`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "periodUnit"`);
        await queryRunner.query(`CREATE TYPE "ranking"."enum_Systems_periodUnit" AS ENUM('months', 'weeks', 'days')`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "periodUnit" "ranking"."enum_Systems_periodUnit"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "periodAmount"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "periodAmount" integer`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "calculationIntervalUnit"`);
        await queryRunner.query(`CREATE TYPE "ranking"."enum_Systems_calculationIntervalUnit" AS ENUM('months', 'weeks', 'days')`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "calculationIntervalUnit" "ranking"."enum_Systems_calculationIntervalUnit"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ALTER COLUMN "calculationIntervalAmount" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ALTER COLUMN "calculationDayOfWeek" SET DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "calculationLastUpdate"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "calculationLastUpdate" TIMESTAMP WITH TIME ZONE DEFAULT '2016-08-31 22:00:00+00'`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "inactiveBehavior"`);
        await queryRunner.query(`CREATE TYPE "ranking"."enum_RankingSystems_inactiveBehavior" AS ENUM('freeze', 'decrease')`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "inactiveBehavior" "ranking"."enum_RankingSystems_inactiveBehavior"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "inactivityUnit"`);
        await queryRunner.query(`CREATE TYPE "ranking"."enum_Systems_inactivityUnit" AS ENUM('months', 'weeks', 'days')`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "inactivityUnit" "ranking"."enum_Systems_inactivityUnit"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ALTER COLUMN "inactivityAmount" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ALTER COLUMN "gamesForInactivty" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ALTER COLUMN "maxLevelDownPerChange" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ALTER COLUMN "maxLevelUpPerChange" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ALTER COLUMN "latestXGamesToUse" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ALTER COLUMN "maxDiffLevelsHighest" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ALTER COLUMN "maxDiffLevels" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ALTER COLUMN "minNumberOfGamesUsedForDowngrade" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ALTER COLUMN "minNumberOfGamesUsedForUpgrade" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "procentLosing"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "procentLosing" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "procentWinningPlus1"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "procentWinningPlus1" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "procentWinning"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "procentWinning" numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ALTER COLUMN "amountOfLevels" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD CONSTRAINT "Systems_name_key" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystemRankingGroupMemberships" DROP COLUMN "groupId"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystemRankingGroupMemberships" ADD "groupId" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystemRankingGroupMemberships" DROP CONSTRAINT "PK_bf1f20730bbad18ddf6fe95b45a"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystemRankingGroupMemberships" ADD CONSTRAINT "GroupSystems_pkey" PRIMARY KEY ("groupId", "rankingSystemRankingGroupMembershipId")`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystemRankingGroupMemberships" DROP CONSTRAINT "GroupSystems_pkey"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystemRankingGroupMemberships" ADD CONSTRAINT "GroupSystems_pkey" PRIMARY KEY ("groupId", "systemId", "rankingSystemRankingGroupMembershipId")`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingGroups" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingGroups" ADD "name" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingGroups" ADD CONSTRAINT "Groups_name_key" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingGroups" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingGroups" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingGroups" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingGroups" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingGroups" DROP CONSTRAINT "PK_444b4810c1a20aa442417cd6b94"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingGroups" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingGroups" ADD "id" character varying(255) NOT NULL DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingGroups" ADD CONSTRAINT "Groups_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" DROP COLUMN "start"`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" DROP COLUMN "confirmed"`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" DROP COLUMN "end"`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" DROP CONSTRAINT "GamePlayers_pkey"`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" ADD CONSTRAINT "GamePlayers_pkey" PRIMARY KEY ("playerId", "gameId")`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystems" DROP COLUMN "rankingSystemRankingGroupMembershipRankingSystemRankingGroupMembershipId"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystemRankingGroupMemberships" DROP COLUMN "rankingGroupId"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystemRankingGroupMemberships" DROP COLUMN "rankingSystemId"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystemRankingGroupMemberships" DROP CONSTRAINT "GroupSystems_pkey"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystemRankingGroupMemberships" ADD CONSTRAINT "GroupSystems_pkey" PRIMARY KEY ("groupId", "systemId")`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystemRankingGroupMemberships" DROP COLUMN "rankingSystemRankingGroupMembershipId"`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingGroups" DROP COLUMN "rankingSystemRankingGroupMembershipRankingSystemRankingGroupMembershipId"`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" ADD "systemId" uuid`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" ADD "mix" integer`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" ADD "double" integer`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" ADD "single" integer`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" ADD "player" integer`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" ADD "team" integer`);
        await queryRunner.query(`CREATE TYPE "event"."enum_Games_status" AS ENUM('NORMAL', 'WALKOVER', 'RETIREMENT', 'DISQUALIFIED', 'NO_MATCH')`);
        await queryRunner.query(`ALTER TABLE "event"."Games" ADD "status" "event"."enum_Games_status"`);
        await queryRunner.query(`CREATE TYPE "event"."enum_Games_gameType" AS ENUM('S', 'D', 'MX')`);
        await queryRunner.query(`ALTER TABLE "event"."Games" ADD "gameType" "event"."enum_Games_gameType"`);
        await queryRunner.query(`CREATE TYPE "public"."enum_ClubPlayerMemberships_membershipType" AS ENUM('NORMAL', 'LOAN')`);
        await queryRunner.query(`ALTER TABLE "ClubPlayerMemberships" ADD "membershipType" "public"."enum_ClubPlayerMemberships_membershipType" NOT NULL DEFAULT 'NORMAL'`);
        await queryRunner.query(`ALTER TABLE "ClubPlayerMemberships" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "ClubPlayerMemberships" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE TYPE "public"."enum_Clubs_useForTeamName" AS ENUM('name', 'fullName', 'abbreviation', 'teamName')`);
        await queryRunner.query(`ALTER TABLE "Clubs" ADD "useForTeamName" "public"."enum_Clubs_useForTeamName" DEFAULT 'name'`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ADD CONSTRAINT "lastPlaces_unique_constraint" UNIQUE ("playerId", "systemId")`);
        await queryRunner.query(`ALTER TABLE "Players" ADD CONSTRAINT "Players_firstName_lastName_memberId_key" UNIQUE ("firstName", "lastName", "memberId")`);
        await queryRunner.query(`ALTER TABLE "ClubPlayerMemberships" ADD CONSTRAINT "ClubMemberships_playerId_clubId_start_key" UNIQUE ("playerId", "clubId", "start")`);
        await queryRunner.query(`ALTER TABLE "Clubs" ADD CONSTRAINT "club_number_unique" UNIQUE ("name", "clubId")`);
        await queryRunner.query(`CREATE UNIQUE INDEX "lastPlaces_ranking_index" ON "ranking"."RankingLastPlaces" ("playerId", "systemId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "players_slug" ON "Players" ("slug") `);
        await queryRunner.query(`CREATE INDEX "players_member_id" ON "Players" ("memberId") `);
        await queryRunner.query(`CREATE INDEX "players_last_name" ON "Players" ("lastName") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "players_id" ON "Players" ("id") `);
        await queryRunner.query(`CREATE INDEX "players_first_name" ON "Players" ("firstName") `);
        await queryRunner.query(`CREATE INDEX "game_players_player_id" ON "event"."GamePlayerMemberships" ("playerId") `);
        await queryRunner.query(`CREATE INDEX "game_players_game_id" ON "event"."GamePlayerMemberships" ("gameId") `);
        await queryRunner.query(`CREATE INDEX "game_parent_index" ON "event"."Games" ("linkId", "linkType") `);
        await queryRunner.query(`CREATE INDEX "player_club_index" ON "ClubPlayerMemberships" ("playerId", "clubId") `);
        await queryRunner.query(`CREATE INDEX "clubs_name" ON "Clubs" ("name") `);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ADD CONSTRAINT "LastPlaces_systemId_fkey" FOREIGN KEY ("systemId") REFERENCES "ranking"."RankingSystems"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingLastPlaces" ADD CONSTRAINT "LastPlaces_playerId_fkey" FOREIGN KEY ("playerId") REFERENCES "Players"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" ADD CONSTRAINT "GamePlayers_playerId_fkey" FOREIGN KEY ("playerId") REFERENCES "Players"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" ADD CONSTRAINT "GamePlayers_gameId_fkey" FOREIGN KEY ("gameId") REFERENCES "event"."Games"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "event"."GamePlayerMemberships" ADD CONSTRAINT "GamePlayerMemberships_systemId_fkey" FOREIGN KEY ("systemId") REFERENCES "ranking"."RankingSystems"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "event"."Games" ADD CONSTRAINT "Games_courtId_fkey" FOREIGN KEY ("courtId") REFERENCES "event"."Courts"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "ClubPlayerMemberships" ADD CONSTRAINT "ClubMemberships_playerId_fkey" FOREIGN KEY ("playerId") REFERENCES "Players"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "ClubPlayerMemberships" ADD CONSTRAINT "ClubMemberships_clubId_fkey" FOREIGN KEY ("clubId") REFERENCES "Clubs"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystemRankingGroupMemberships" ADD CONSTRAINT "GroupSystems_systemId_fkey" FOREIGN KEY ("systemId") REFERENCES "ranking"."RankingSystems"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "ranking"."RankingSystemRankingGroupMemberships" ADD CONSTRAINT "GroupSystems_groupId_fkey" FOREIGN KEY ("groupId") REFERENCES "ranking"."RankingGroups"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

}
